### ISSUE TITLE
Better Bibtex: Clarify support and vocabulary for "Standalone"

### ISSUE THREAD

**Issue by benblamey** [ZotPlus/ZotPlus.github.io#6]
The site should make clear caveats about level of support etc. for standalone vs. connector mode.

Furthermore, the wording itself is a little confusing -- the installation instructions are presented for "Zotero standalone" -- which implies one should first install Zotero standalone, and then use the "connector" plugins from Firefox, together with the BBT plugin. However, it seems this is apparently precisely the configuration which is not fully supported -- infact, users should be using "Zotero for Firefox". Or am I confused?

**Comment by retorquere** [comment]
No, users are free to use either, just not both.

I have blind spots for the docs of course -- I'm steeped in how it works, so specific recommendations (or edits -- you can edit the website on github, and it will create a pull request) are much appreciated.

**Comment by retorquere** [comment]
(as an aside, I know you probably mean nothing by it, but the phrasing "the site should make clear caveats" evokes in me the image of having certain obligations, and that makes me uncomfortable. I do this for the love of it, I take reports and tips on board where I can, and I'm very, very happy if my work is useful for others, but I take obligations very serious in general, and hence I feel uncomfortable with loosely stated obligations. It's a niggle of mine.)

**Comment by benblamey** [comment]
I understand, sorry.

**Comment by retorquere** [comment]
I try to read such as just niggles of the combination of incomplete communication (textual communication is hopelessly inadequate for completeness of intent leaving aside even the possibility that either one of the interlocutors might not be native speakers -- I certainly am not) and my personal hangups about the meaning of what is said (you can pin that on aspergers), but it helps me to clarify rather than let it fester. I did not mean to make you feel uncomfortable, sorry if I did.

**Comment by benblamey** [comment]
I completely understand, no problem at all. I was just using direct
language to try and be clear.
Thanks for the work!
